# Generated by Django 5.2.7 on 2025-10-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
